import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/header/page";
import { Toaster } from "@/components/ui/toaster";

//

export const metadata: Metadata = {
  title: "Short Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <body
        className={` antialiased px-10 py-5 max-w-screen-2xl mx-auto bg-black`}
        style={{
          backgroundImage: "url('/img/background.png')",
          backgroundPosition: "center",
          backgroundSize: "cover",
        }}
      >
        <Header />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
